### ISSUE TITLE
WOA crashing when starting Flash FFU

### ISSUE THREAD

**Issue by paulanthony12** [WOA-Project/WOA-Device-Manager#1]
Seconds after clicking Flash FFU image the app crashes. There are two Error events in the Application Event Log.

Log Name:      Application
Source:        .NET Runtime
Date:          05/07/2024 20:30:50
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-XXXXXXX
Description:
Application: WOADeviceManager.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: UnifiedFlashingPlatform.WPinternalsException: Flash failed!
   at UnifiedFlashingPlatform.UnifiedFlashingPlatformTransport.ThrowFlashError(Int32 ErrorCode)
   at UnifiedFlashingPlatform.UnifiedFlashingPlatformTransport.FlashFFU(FileStream FfuFile, ProgressUpdater UpdaterPerChunk, Boolean ResetAfterwards, Byte Options)
   at WOADeviceManager.Pages.FlashPage.<>c__DisplayClass6_0.<<FlashFFUImageButton_Click>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

AND

Log Name:      Application
Source:        Application Error
Date:          05/07/2024 20:30:51
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          DESKTOP-XXXXXXX\paulj
Computer:      DESKTOP-XXXXXXX
Description:
Faulting application name: WOADeviceManager.exe, version: 1.0.0.0, time stamp: 0x661f0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3733, time stamp: 0x44653e19
Exception code: 0xe0434352
Fault offset: 0x000000000005f39c
Faulting process id: 0x0x4DF8
Faulting application start time: 0x0x1DACF096F99A3BA
Faulting application path: C:\Program Files\WindowsApps\48791GustaveMonce.WOADeviceManager_1.0.7.0_x64__y5tfwz44jfxg4\WOADeviceManager\WOADeviceManager.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 54fdc36b-f4c9-414e-a4e7-38e9c5d53120
Faulting package full name: 48791GustaveMonce.WOADeviceManager_1.0.7.0_x64__y5tfwz44jfxg4
Faulting package-relative application ID: App

**Comment by gus33000** [comment]
The FFU file you selected is not for this device or is corrupted.

(ie, you downloaded a file for a 256GB device and are trying to flash it on a 128GB device or you downloaded a file for a duo 2 when you have a duo 1 or vice versa, or you half downloaded the file.)

Recheck and try again

**Comment by paulanthony12** [comment]
That was exactly the problem, thanks. I found the correct FFU file and everything sailed through perfectly.
